theme: jekyll-theme-cayman
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - csmap_url_historian.md
  - csmap_testing_instructions.md
  - csmap_url_historian_es.md
  - csmap_privacy_policy.md
  - survey_instructions_pt3.md
  - survey_instructions_pt4.md
  - survey_instructions_pt5.md
